### ISSUE TITLE
Not executing.

### ISSUE THREAD

**Issue by hOdOrNight** [tushcoder/ThreeAddressCode#1]

**Comment by tushcoder** [comment]
It will not compile like this, you need to pass proper flags. I think you do not have proper lex and yacc setup. Please use make file provided with it to generate binary once you have proper setup.
You may some some warnings but should not have any error. 
Last year, I got an email from a student who tried to use it and it worked perfectly on his machine. I used it around 4 years back as part of some college project and was using Ubuntu at that time.
